apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  # The name of the volume. This will be how it is identified via 
  # persistent volume claims or from pods.
  name: "pv0001"
spec:
  capacity:
    storage: "500Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    # This is the GCE Persistent Disk volume that will be used.
    pdName: "pd-disk-1"