# Kube-Lego automatically requests missing or expired certificates 
# from Let's Encrypt by monitoring ingress resources and its referenced 
# secrets. To enable this for an ingress resource you have to add an annotation:
# `kubectl annotate ing ingress-demo kubernetes.io/tls-acme="true"`
# The only change necessary is setting your email address and maybe
# the Let's Encrypt API (choose production or not)
# The resources will be created in the order they appear in the file. 
apiVersion: v1
metadata:
  name: kube-lego
  namespace: nginx-ingress
data:
  # modify this to specify your address
  lego.email: "dan.stroot@gmail.com"  #<<<<<<<<<<
  # configure letencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-lego
  namespace: nginx-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-lego
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: kube-lego
        image: jetstack/kube-lego:0.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: LEGO_EMAIL
          valueFrom:
            configMapKeyRef:
              name: kube-lego
              key: lego.email
        - name: LEGO_URL
          valueFrom:
            configMapKeyRef:
              name: kube-lego
              key: lego.url
        - name: LEGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
