apiVersion: v1
entries:
  minio:
  - apiVersion: v1
    created: 2017-06-15T17:48:36.895822482Z
    description: Distributed object storage server built for cloud applications and
      devops.
    digest: 75ff1e3d779d8937cff57c28a102da97a520245d50e22c1a2763cbea064a76cd
    home: https://minio.io
    icon: https://www.minio.io/img/logo_160x160.png
    keywords:
    - storage
    - object-storage
    - S3
    maintainers:
    - email: hello@acale.ph
      name: Acaleph
    - email: hello@minio.io
      name: Minio
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - https://bruinboi_helm.storage.googleapis.com/minio-0.1.2.tgz
    version: 0.1.2